# render.yaml
services:
  - type: web
    name: inventory-app
    env: python
    region: oregon # choose your preferred region
    plan: free     # or starter/pro
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DB_HOST
        value: <localhost>
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: <IMApp>
      - key: DB_USER
        value: <postgres>
      - key: DB_PASSWORD
        value: <HDS800516usa>